version: "3.9"
services:
  mosquitto:
    container_name: BrokerMQTT
    image: eclipse-mosquitto:latest
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf

  influxdb:
    container_name: influxdb
    image: influxdb:2.4.0-alpine
    volumes:
      - influxdb-lib:/var/lib/influxdb2
    env_file:
      # BE SURE TO CHANGE THIS LINE BEFORE GOING TO PRODUCTION
      - ./influx2.env
    ports:
      - 8086:8086
    restart: always
    privileged: true

  grafana:
    container_name: grafana
    image: grafana/grafana-oss:9.1.8
    volumes:
      - ./grafana/etc:/etc/grafana:ro
      - grafana-lib:/var/lib/grafana
      - grafana-log:/var/log/grafana
    links:
      - influxdb:influxdb
    env_file:
      # BE SURE TO CHANGE THIS LINE BEFORE GOING TO PRODUCTION
      - ./grafana.env
    ports:
      - 8080:3000
    depends_on:
      - influxdb
    restart: always
    privileged: true

volumes:
  influxdb-lib:
    external: false

  grafana-lib:
    external: false

  grafana-log:
    external: false
