version: "3.9"
services:
  brokerMQTT:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mosquitto:/mydata
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/log/mosquitto.log:/mosquitto/log/mosquitto.log
    deploy:
      placement:
        constraints:
          - "node.role==manager"
      restart_policy:
        condition: on-failure

  publishMQTT:
    image: 127.0.0.1:5000/publishmqtt:latest
    depends_on:
      - brokerMQTT
    deploy:
      placement:
        constraints:
          - "node.role==worker"

  subscribeMQTT:
    image: 127.0.0.1:5000/subscribemqtt:latest
    depends_on:
      - publishMQTT
    deploy:
      placement:
        constraints:
          - "node.role==worker"
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints:
          - "node.role==manager"
      restart_policy:
        condition: on-failure

  influxdb:
    image: influxdb:2.4.0-alpine
    volumes:
      - influxdb-lib:/var/lib/influxdb2
    env_file:
      - ./influx2.env
    ports:
      - 8086:8086
    restart: always
    privileged: true

  grafana:
    user: "0"
    image: grafana/grafana-oss:9.1.8
    volumes:
      - ./grafana/etc:/etc/grafana:ro
      - grafana-lib:/var/lib/grafana
      - grafana-log:/var/log/grafana

    env_file:
      - ./grafana.env
    ports:
      - 3000:3000
    depends_on:
      - influxdb
    restart: always
    privileged: true

volumes:
  influxdb-lib:
  grafana-lib:
  grafana-log:
  mosquitto:
    driver_opts:
      type: "nfs"
      o: "addr=10.150.2.15,nolock,rw,soft"
      device: ":/mosquitto"
