---
- name: Setup pre-requisites
  hosts: all
  roles:
    - install-modules

- name: Install docker
  hosts: docker-nodes
  roles:
    - docker-installation

- name: Initialize docker swarm
  hosts: swarm-manager
  roles:
    - docker-swarm-init

- name: Add workers to the swarm
  hosts: swarm-workers
  roles:
    - docker-swarm-add-worker
