- name: Install Docker on nodes
  hosts: dockernodes
  become: true
  tasks:
     - name: Set up pre-requirements package
       apt:
        pkg:
          - ansible.builtin.apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools

        state: latest
        update_cache: true

   
     - name: Add Docker's official GPG ley
       ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present 

     - name: Add Docker Repository
       apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

     - name: Update apt and install docker-ce
       apt:
        name: docker-ce
        state: latest
        update_cache: true

     - name: Install Docker Module for Python
       pip:
        name: docker

     - name: Install Docker Compose
       apt:
        name: docker-compose-plugin
        state: latest
        update_cache: true
