---
- name: Install Packages
  ansible.builtin.apt:
    name:
      - ntp
      - python3-pip
      - virtualenv
      - python3-setuptools
      - tcpdump
      - wget
      - openssl
      - curl
    state: present
    update_cache: true
