---
- name: Check if Swarm has already been Initialized
  ansible.builtin.command: docker node ls
  register: swarm_status
  ignore_errors: true
  tags: swarm

- name: Initialize Docker Swarm
  community.docker.docker_swarm:
    state: present
    default_addr_poll: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
  when: swarm_status.rc != 0
  run_once: true
  tags: swarm

- name: Get the Manager join-token
  ansible.builtin.command: docker swarm join-token --quiet manager
  register: manager_token
  changed_when: manager_token.rc != 0
  tags: swarm

- name: Get the worker join-token
  ansible.builtin.command: docker swarm join-token --quiet worker
  register: worker_token
  changed_when: worker_token.rc != 0
  tags: swarm
